version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3500:3500"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
